cycamore: cycamore::SinkFacility Class Reference
cycamore::SinkFacility Class Reference
This cyclus::FacilityModel requests a finite amount of its input commodity.
#include <sink_facility.h>
Public Member Functions
virtual void AcceptGenRsrcTrades (const std::vector< std::pair< cyclus::Trade< cyclus::GenericResource >, cyclus::GenericResource::Ptr > > &responses)
SinkFacilities place accepted trade Materials in their Inventory.
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
SinkFacilities place accepted trade Materials in their Inventory.
void AddCommodity (std::string name)
add a commodity to the set of input commodities
void capacity (double capacity)
sets the capacity of a material generated at any given time step
double capacity () const
virtual cyclus::Model * Clone ()
virtual std::set
< cyclus::RequestPortfolio
< cyclus::GenericResource >
::Ptr > GetGenRsrcRequests ()
SinkFacilities request GenericResources of their given commodity.
virtual std::set
< cyclus::RequestPortfolio
< cyclus::Material >::Ptr > GetMatlRequests ()
SinkFacilities request Materials of their given commodity.
void InitFrom (SinkFacility *m)
initialize members from a different model
virtual void InitModuleMembers (cyclus::QueryEngine *qe)
Initialize members related to derived module class.
const std::vector< std::string > & input_commodities () const
double InventorySize () const
double MaxInventorySize () const
double RequestAmt () const
determines the amount to request
virtual std::string schema ()
void SetMaxInventorySize (double size)
sets the size of the storage inventory for received material
SinkFacility (cyclus::Context *ctx)
Constructor for the SinkFacility class.
virtual std::string str ()
A verbose printer for the Sink Facility.
virtual void Tick (int time)
The SinkFacility can handle the Tick.
virtual void Tock (int time)
The SinkFacility can handle the Tock.
virtual ~SinkFacility ()
Destructor for the SinkFacility class.
Private Attributes
double capacity_
monthly acceptance capacity
double commod_price_
commodity price
std::vector< std::string > in_commods_
all facilities must have at least one input commodity
cyclus::ResourceBuff inventory_
this facility holds material in storage.
Detailed Description
This cyclus::FacilityModel requests a finite amount of its input commodity.
It offers nothing.
The SinkFacility class inherits from the cyclus::FacilityModel class and is dynamically loaded by the Model class when requested.
Introduction
The SinkFacility is a facility type in *Cyclus* capable of accepting a finite or infinite quantity of some commodity produced in the simulation. A SinkFacility requests an amount of that commodity from the appropriate market. It then receives that commodity when the market issues an order that the request has been matched with a corresponding offer.
Model Parameters
SinkFacility behavior is comprehensively defined by the following parameters:
double capacity: The acceptance capacity of the facility (units vary, but typically kg/month). Capacity is infinite if a positive value is provided.
int startDate: The date on which the facility begins to operate (months). - int lifeTime: The length of time that the facility operates (months). - std::string inCommod: The commodity type this facility accepts.
Optional Parameters
SinkFacility behavior may also be specified with the following optional parameters which have default values listed here.
double capacityFactor: The ratio of actual acceptance capacity to the rated acceptance capacity. Default is 1 (actual/rated).
double availFactor: The percent of time the facility operates at its capacity factor. Default is 100%.
double capitalCost: The cost of constructing and commissioning this facility. Default is 0 ($).
double opCost: The annual cost of operation and maintenance of this facility. Default is 0 ($/year).
int constrTime: The number of months it takes to construct and commission this facility. Default is 0 (months).
int decomTime: The number of months it takes to deconstruct and decommission this facility. Default is 0 (months).
Inst* inst: The institution responsible for this facility.
string name: A non-generic name for this facility.
Detailed Behavior
If Finite Capacity:
The SinkFacility starts operation when the simulation reaches the month specified as the startDate. It immediately begins to request the inCommod commodity type at the rate defined by the SinkFacility capacity. If a request is matched with an offer from another facility, the SinkFacility executes that order by adding that quantity to its stocks. When the simulation time equals the startDate plus the lifeTime, the facility ceases to operate.
If Infinite Capacity:
The SinkFacility starts operation when the simulation reaches the month specified as the startDate. Each month the SinkFacility requests an infinite amount of the inCommod commodity from the appropriate market. If there is a corresponding offer for that commodity type from another facility, the SinkFacility executes that order by adding that quantity to its stocks. When the simulation time equals the startDate plus the lifeTime, the facility ceases to operate.
Question:
What is the best way to allow requests of an infinite amount of material on a market?
Definition at line 89 of file sink_facility.h.
Constructor & Destructor Documentation
cycamore::SinkFacility::SinkFacility (cyclus::Context * ctx)
Constructor for the SinkFacility class.
Parameters:
ctx the cyclus context for access to simulation-wide parameters
Definition at line 19 of file sink_facility.cc.
References SetMaxInventorySize().
Referenced by Clone().
cycamore::SinkFacility::~SinkFacility () [virtual]
Destructor for the SinkFacility class.
Definition at line 28 of file sink_facility.cc.
Member Function Documentation
void cycamore::SinkFacility::AcceptGenRsrcTrades (const std::vector< std::pair< cyclus::Trade< cyclus::GenericResource >, cyclus::GenericResource::Ptr > > & responses) [virtual]
SinkFacilities place accepted trade Materials in their Inventory.
Definition at line 182 of file sink_facility.cc.
References inventory_.
void cycamore::SinkFacility::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
SinkFacilities place accepted trade Materials in their Inventory.
Definition at line 171 of file sink_facility.cc.
References inventory_.
void cycamore::SinkFacility::AddCommodity (std::string name) [inline]
add a commodity to the set of input commodities
Parameters:
name the commodity name
Definition at line 168 of file sink_facility.h.
References in_commods_.
Referenced by InitModuleMembers(), and SinkFacilityTest::SetUpSinkFacility().
void cycamore::SinkFacility::capacity (double capacity) [inline]
sets the capacity of a material generated at any given time step
Parameters:
capacity the reception capacity
Definition at line 193 of file sink_facility.h.
References capacity(), and capacity_.
Referenced by capacity(), InitFrom(), and SinkFacilityTest::SetUpSinkFacility().
double cycamore::SinkFacility::capacity () const [inline]
Returns:
the reception capacity at any given time step
Definition at line 196 of file sink_facility.h.
References capacity_.
Referenced by InitFrom(), and InitModuleMembers().
cyclus::Model * cycamore::SinkFacility::Clone () [virtual]
Definition at line 94 of file sink_facility.cc.
References InitFrom(), and SinkFacility().
std::set< cyclus::RequestPortfolio< cyclus::GenericResource >::Ptr > cycamore::SinkFacility::GetGenRsrcRequests () [virtual]
SinkFacilities request GenericResources of their given commodity.
Note that it is assumed the SinkFacility operates on a single resource type!
Definition at line 139 of file sink_facility.cc.
References in_commods_, and RequestAmt().
std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > cycamore::SinkFacility::GetMatlRequests () [virtual]
SinkFacilities request Materials of their given commodity.
Note that it is assumed the SinkFacility operates on a single resource type!
Definition at line 111 of file sink_facility.cc.
References in_commods_, and RequestAmt().
void cycamore::SinkFacility::InitFrom (SinkFacility * m)
initialize members from a different model
Definition at line 101 of file sink_facility.cc.
References capacity(), in_commods_, MaxInventorySize(), and SetMaxInventorySize().
Referenced by Clone().
void cycamore::SinkFacility::InitModuleMembers (cyclus::QueryEngine * qe) [virtual]
Initialize members related to derived module class.
Parameters:
qe a pointer to a cyclus::QueryEngine object containing initialization data
Definition at line 49 of file sink_facility.cc.
References AddCommodity(), capacity(), and SetMaxInventorySize().
const std::vector<std::string>& cycamore::SinkFacility::input_commodities () const [inline]
Returns:
the input commodities
Definition at line 200 of file sink_facility.h.
References in_commods_.
double cycamore::SinkFacility::InventorySize () const [inline]
Returns:
the current inventory storage size
Definition at line 180 of file sink_facility.h.
References inventory_.
double cycamore::SinkFacility::MaxInventorySize () const [inline]
Returns:
the maximum inventory storage size
Definition at line 177 of file sink_facility.h.
References inventory_.
Referenced by InitFrom().
double cycamore::SinkFacility::RequestAmt () const [inline]
determines the amount to request
Definition at line 185 of file sink_facility.h.
References capacity_, and inventory_.
Referenced by GetGenRsrcRequests(), GetMatlRequests(), and Tick().
std::string cycamore::SinkFacility::schema () [virtual]
Definition at line 31 of file sink_facility.cc.
void cycamore::SinkFacility::SetMaxInventorySize (double size) [inline]
sets the size of the storage inventory for received material
Parameters:
size the storage size
Definition at line 174 of file sink_facility.h.
References inventory_.
Referenced by InitFrom(), InitModuleMembers(), SinkFacilityTest::SetUpSinkFacility(), and SinkFacility().
std::string cycamore::SinkFacility::str () [virtual]
A verbose printer for the Sink Facility.
Definition at line 74 of file sink_facility.cc.
References in_commods_, and inventory_.
void cycamore::SinkFacility::Tick (int time) [virtual]
The SinkFacility can handle the Tick.
Parameters:
time the current simulation time.
Definition at line 193 of file sink_facility.cc.
References in_commods_, and RequestAmt().
void cycamore::SinkFacility::Tock (int time) [virtual]
The SinkFacility can handle the Tock.
Parameters:
time the current simulation time.
Definition at line 212 of file sink_facility.cc.
References inventory_.
Member Data Documentation
double cycamore::SinkFacility::capacity_ [private]
monthly acceptance capacity
Definition at line 211 of file sink_facility.h.
Referenced by capacity(), and RequestAmt().
double cycamore::SinkFacility::commod_price_ [private]
commodity price
Definition at line 216 of file sink_facility.h.
std::vector<std::string> cycamore::SinkFacility::in_commods_ [private]
all facilities must have at least one input commodity
Definition at line 206 of file sink_facility.h.
Referenced by AddCommodity(), GetGenRsrcRequests(), GetMatlRequests(), InitFrom(), input_commodities(), str(), and Tick().
cyclus::ResourceBuff cycamore::SinkFacility::inventory_ [private]
this facility holds material in storage.
Definition at line 221 of file sink_facility.h.
Referenced by AcceptGenRsrcTrades(), AcceptMatlTrades(), InventorySize(), MaxInventorySize(), RequestAmt(), SetMaxInventorySize(), str(), and Tock().
The documentation for this class was generated from the following files:
sink_facility.h
sink_facility.cc