cycamore: cycamore::ManagerInst Class Reference
cycamore::ManagerInst Class Reference
#include <manager_inst.h>
Public Member Functions
virtual cyclus::Model * Clone ()
void InitFrom (ManagerInst *m)
ManagerInst (cyclus::Context *ctx)
Default constructor.
virtual void RegisterAvailablePrototype (std::string prototype)
perform any actions required after prototype has been added to the list of available prototypes
virtual void RegisterCloneAsBuilt (cyclus::Model *clone)
perform any registration functionality after a clone has been built
virtual void RegisterCloneAsDecommissioned (cyclus::Model *clone)
perform any registration functionality before a clone is decommissioned(deleted)
void WriteProducerInformation (cyclus::CommodityProducer *producer)
write information about a commodity producer to a stream
virtual ~ManagerInst ()
Default destructor.
Detailed Description
Introduction
Detailed Behavior
Definition at line 19 of file manager_inst.h.
Constructor & Destructor Documentation
cycamore::ManagerInst::ManagerInst (cyclus::Context * ctx)
Default constructor.
Definition at line 10 of file manager_inst.cc.
Referenced by Clone().
cycamore::ManagerInst::~ManagerInst () [virtual]
Default destructor.
Definition at line 15 of file manager_inst.cc.
Member Function Documentation
virtual cyclus::Model* cycamore::ManagerInst::Clone () [inline, virtual]
Definition at line 33 of file manager_inst.h.
References InitFrom(), and ManagerInst().
void cycamore::ManagerInst::InitFrom (ManagerInst * m) [inline]
Definition at line 39 of file manager_inst.h.
Referenced by Clone().
void cycamore::ManagerInst::RegisterAvailablePrototype (std::string prototype) [virtual]
perform any actions required after prototype has been added to the list of available prototypes
Parameters:
prototype the prototype to register
Definition at line 18 of file manager_inst.cc.
void cycamore::ManagerInst::RegisterCloneAsBuilt (cyclus::Model * clone) [virtual]
perform any registration functionality after a clone has been built
Parameters:
clone the built (cloned) prototype
Definition at line 33 of file manager_inst.cc.
References WriteProducerInformation().
void cycamore::ManagerInst::RegisterCloneAsDecommissioned (cyclus::Model * clone) [virtual]
perform any registration functionality before a clone is decommissioned(deleted)
Parameters:
clone the to-be-decommissioned prototype
Definition at line 47 of file manager_inst.cc.
void cycamore::ManagerInst::WriteProducerInformation (cyclus::CommodityProducer * producer)
write information about a commodity producer to a stream
Parameters:
producer the producer
Definition at line 56 of file manager_inst.cc.
Referenced by RegisterCloneAsBuilt().
The documentation for this class was generated from the following files:
manager_inst.h
manager_inst.cc