cycamore: cycamore::SourceFacility Class Reference
cycamore::SourceFacility Class Reference
This cyclus::FacilityModel provides a simple source of some capacity (possibly infinite) of some commodity/Recipe.
#include <source_facility.h>
Public Member Functions
void capacity (double capacity)
sets the capacity of a material generated at any given time step
double capacity () const
virtual cyclus::Model * Clone ()
void commodity (std::string name)
sets the output commodity name
std::string commodity () const
double current_capacity () const
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (const cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this source facility's commodity.
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material made from this facility's recipe
cyclus::Material::Ptr GetOffer (const cyclus::Material::Ptr target) const
creates a material object to offer to a requester
void InitFrom (SourceFacility *m)
initialize members from a different model
virtual void InitModuleMembers (cyclus::QueryEngine *qe)
Initialize members related to derived module class.
void recipe (std::string name)
sets the name of the recipe to be produced
std::string recipe () const
virtual std::string schema ()
SourceFacility (cyclus::Context *ctx)
Constructor for the SourceFacility class.
virtual std::string str ()
Print information about this model.
virtual void Tick (int time)
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
virtual void Tock (int time)
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
virtual ~SourceFacility ()
Private Attributes
double capacity_
The capacity is defined in terms of the number of units of the recipe that can be provided each time step.
double commod_price_
The price that the facility will charge for its output commodity.
double current_capacity_
The capacity at the current time step.
std::string out_commod_
This facility has only one output commodity.
std::string recipe_name_
Name of the recipe this facility uses.
Detailed Description
This cyclus::FacilityModel provides a simple source of some capacity (possibly infinite) of some commodity/Recipe.
The SourceFacility class inherits from the cyclus::FacilityModel class and is dynamically loaded by the Model class when requested.
Introduction
The SourceFacility is a facility type in Cyclus capable of providing a finite or infinite.Supply of a particular material to the simulation. A SourceFacility generates material of a certain composition and commodity type, then offers that material on the appropriate market. Shipments of this material are executed when the market issues an order that the offer has been matched with a request.
Model Parameters
SourceFacility behavior is comprehensively defined by the following parameters:
double capacity: The production capacity of the facility (units vary, but typically kg/month). Capacity is infinite if a negative value is provided.
int startDate: The date on which the facility begins to operate (months).
int lifeTime: The length of time that the facility operates (months). - std::string outCommod: the commodity that this facility produces - double inventorysize: the maximum quantity of material to be held in the inventory
double commodprice: the price of the output material PER UNIT
map<Isos, NumDens> outComp
Optional Parameters
SourceFacility behavior may also be specified with the following optional parameters which have default values listed here.
double capacityFactor: The ratio of actual production capacity to the rated production capacity. Default is 1 (actual/rated).
double availFactor: The percent of time the facility operates at its capacity factor. Default is 100%.
double capitalCost: The cost of constructing and commissioning this facility. Default is 0 ($).
double opCost: The annual cost of operation and maintenance of this facility. Default is 0 ($/year).
int constrTime: The number of months it takes to construct and commission this facility. Default is 0 (months).
int decomTime: The number of months it takes to deconstruct and decommission this facility. Default is 0 (months).
Inst* inst: The institution responsible for this facility.
string name: A non-generic name for this facility.
Detailed Behavior
If Finite Capacity:
The SourceFacility starts operation when the simulation reaches the month specified as the startDate. It immediately begins to produce material at the rate defined by its capacity. Each month the SourceFacility adds the amount it has produced to its inventory. It then offers to the appropriate market exactly as much material as it has in its inventory. If an offer is matched with a request, the SourceFacility executes that order by subtracting the quantity from its inventory and sending that amount to the requesting facility. When the simulation time equals the startDate plus the lifeTime, the facility ceases to operate.
If Infinite Capacity:
The SourceFacility starts operation when the simulation reaches the month specified as the startDate. Each month the SourceFacility offers an infinite amount of material to the appropriate market. If there is a request for that material, the SourceFacility executes that order by sending that amount to the requesting facility. When the simulation time equals the startDate plus the lifeTime, the facility ceases to operate.
Question:
What is the best way to allow offers of an infinite amount of material on a market?
Definition at line 94 of file source_facility.h.
Constructor & Destructor Documentation
cycamore::SourceFacility::SourceFacility (cyclus::Context * ctx)
Constructor for the SourceFacility class.
Parameters:
ctx the cyclus context for access to simulation-wide parameters
Definition at line 20 of file source_facility.cc.
Referenced by Clone().
cycamore::SourceFacility::~SourceFacility () [virtual]
Definition at line 29 of file source_facility.cc.
Member Function Documentation
void cycamore::SourceFacility::capacity (double capacity) [inline]
sets the capacity of a material generated at any given time step
Parameters:
capacity the production capacity
Definition at line 184 of file source_facility.h.
References capacity(), capacity_, and current_capacity_.
Referenced by InitFrom(), SourceFacilityTest::SetUpSourceFacility(), and TEST_F().
double cycamore::SourceFacility::capacity () const [inline]
Returns:
the production capacity at any given time step
Definition at line 190 of file source_facility.h.
References capacity_.
Referenced by capacity(), InitFrom(), and InitModuleMembers().
cyclus::Model * cycamore::SourceFacility::Clone () [virtual]
Definition at line 78 of file source_facility.cc.
References InitFrom(), and SourceFacility().
void cycamore::SourceFacility::commodity (std::string name) [inline]
sets the output commodity name
Parameters:
name the commodity name
Definition at line 175 of file source_facility.h.
References out_commod_.
Referenced by InitFrom(), SourceFacilityTest::SetUpSourceFacility(), and TEST_F().
std::string cycamore::SourceFacility::commodity () const [inline]
Returns:
the output commodity
Definition at line 178 of file source_facility.h.
References out_commod_.
Referenced by InitFrom(), and InitModuleMembers().
double cycamore::SourceFacility::current_capacity () const [inline]
Returns:
the current timestep's capacity
Definition at line 202 of file source_facility.h.
References current_capacity_.
Referenced by TEST_F().
std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > cycamore::SourceFacility::GetMatlBids (const cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this source facility's commodity.
If a given request is more than this facility's capacity, it will offer its capacity.
Definition at line 120 of file source_facility.cc.
References capacity_, GetOffer(), and out_commod_.
void cycamore::SourceFacility::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material made from this facility's recipe
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 151 of file source_facility.cc.
References capacity_, current_capacity_, out_commod_, and recipe_name_.
cyclus::Material::Ptr cycamore::SourceFacility::GetOffer (const cyclus::Material::Ptr target) const
creates a material object to offer to a requester
Parameters:
target the material target a request desires
Definition at line 111 of file source_facility.cc.
References capacity_, and recipe_name_.
Referenced by GetMatlBids().
void cycamore::SourceFacility::InitFrom (SourceFacility * m)
initialize members from a different model
Definition at line 85 of file source_facility.cc.
References capacity(), commodity(), current_capacity_, and recipe().
Referenced by Clone().
void cycamore::SourceFacility::InitModuleMembers (cyclus::QueryEngine * qe) [virtual]
Initialize members related to derived module class.
Parameters:
qe a pointer to a cyclus::QueryEngine object containing initialization data
Definition at line 46 of file source_facility.cc.
References capacity(), commodity(), and recipe().
void cycamore::SourceFacility::recipe (std::string name) [inline]
sets the name of the recipe to be produced
Parameters:
name the recipe name
Definition at line 196 of file source_facility.h.
References recipe_name_.
Referenced by InitFrom(), SourceFacilityTest::SetUpSourceFacility(), and TEST_F().
std::string cycamore::SourceFacility::recipe () const [inline]
Returns:
the name of the output recipe
Definition at line 199 of file source_facility.h.
References recipe_name_.
Referenced by InitFrom(), and InitModuleMembers().
std::string cycamore::SourceFacility::schema () [virtual]
Definition at line 32 of file source_facility.cc.
std::string cycamore::SourceFacility::str () [virtual]
Print information about this model.
Definition at line 67 of file source_facility.cc.
References capacity_, out_commod_, and recipe_name_.
void cycamore::SourceFacility::Tick (int time) [virtual]
Each facility is prompted to do its beginning-of-time-step stuff at the tick of the timer.
Parameters:
time is the time to perform the tick
Definition at line 95 of file source_facility.cc.
References capacity_, current_capacity_, and out_commod_.
void cycamore::SourceFacility::Tock (int time) [virtual]
Each facility is prompted to its end-of-time-step stuff on the tock of the timer.
Parameters:
time is the time to perform the tock
Definition at line 105 of file source_facility.cc.
Member Data Documentation
double cycamore::SourceFacility::capacity_ [private]
The capacity is defined in terms of the number of units of the recipe that can be provided each time step.
A very large number can be provided to represent infinte capacity.
Definition at line 220 of file source_facility.h.
Referenced by capacity(), GetMatlBids(), GetMatlTrades(), GetOffer(), str(), and Tick().
double cycamore::SourceFacility::commod_price_ [private]
The price that the facility will charge for its output commodity.
Units vary and are in dollars per inventory unit.
Definition at line 231 of file source_facility.h.
double cycamore::SourceFacility::current_capacity_ [private]
The capacity at the current time step.
Definition at line 225 of file source_facility.h.
Referenced by capacity(), current_capacity(), GetMatlTrades(), InitFrom(), and Tick().
std::string cycamore::SourceFacility::out_commod_ [private]
This facility has only one output commodity.
Definition at line 208 of file source_facility.h.
Referenced by commodity(), GetMatlBids(), GetMatlTrades(), str(), and Tick().
std::string cycamore::SourceFacility::recipe_name_ [private]
Name of the recipe this facility uses.
Definition at line 213 of file source_facility.h.
Referenced by GetMatlTrades(), GetOffer(), recipe(), and str().
The documentation for this class was generated from the following files:
source_facility.h
source_facility.cc