cycamore: cycamore::DeployInst Class Reference
cycamore::DeployInst Class Reference
The DeployInst class inherits from the InstModel class and is dynamically loaded by the Model class when requested.
#include <deploy_inst.h>
Public Member Functions
virtual cyclus::Model * Clone ()
DeployInst (cyclus::Context *ctx)
Default constructor.
virtual void InitModuleMembers (cyclus::QueryEngine *qe)
Initialize members related to derived module class.
virtual std::string schema ()
virtual void Tick (int time)
tick handling function for this inst
virtual ~DeployInst ()
Destructor.
Protected Attributes
BuildOrderList build_orders_
a collection of orders to build
Detailed Description
The DeployInst class inherits from the InstModel class and is dynamically loaded by the Model class when requested.
This model implements a simple institution model that deploys specific facilities as defined explicitly in the input file.
Definition at line 38 of file deploy_inst.h.
Constructor & Destructor Documentation
cycamore::DeployInst::DeployInst (cyclus::Context * ctx)
Default constructor.
Definition at line 45 of file deploy_inst.cc.
Referenced by Clone().
cycamore::DeployInst::~DeployInst () [virtual]
Destructor.
Definition at line 50 of file deploy_inst.cc.
Member Function Documentation
virtual cyclus::Model* cycamore::DeployInst::Clone () [inline, virtual]
Definition at line 56 of file deploy_inst.h.
References DeployInst().
void cycamore::DeployInst::InitModuleMembers (cyclus::QueryEngine * qe) [virtual]
Initialize members related to derived module class.
Parameters:
qe a pointer to a cyclus::QueryEngine object containing initialization data
Definition at line 71 of file deploy_inst.cc.
References cycamore::BuildOrderList::AddBuildOrder(), and build_orders_.
std::string cycamore::DeployInst::schema () [virtual]
Definition at line 53 of file deploy_inst.cc.
void cycamore::DeployInst::Tick (int time) [virtual]
tick handling function for this inst
Definition at line 88 of file deploy_inst.cc.
References build_orders_, and cycamore::BuildOrderList::ExtractOrders().
Member Data Documentation
BuildOrderList cycamore::DeployInst::build_orders_ [protected]
a collection of orders to build
Definition at line 90 of file deploy_inst.h.
Referenced by InitModuleMembers(), and Tick().
The documentation for this class was generated from the following files:
deploy_inst.h
deploy_inst.cc