cycamore: cycamore::InproReactor Class Reference
cycamore::InproReactor Class Reference
This class is identical to the RecipeReactor, except that it operates in a batch-like manner, i.e.
#include <inpro_reactor.h>
Public Member Functions
virtual void AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
The EnrichmentFacility place accepted trade Materials in their Inventory.
int batches_per_core ()
double BatchLoading ()
return the batch loading
virtual cyclus::Model * Clone ()
bool CoreFilled ()
return true if the core is filled
int cycle_length ()
bool CycleComplete ()
return true if the cycle timer is >= the cycle length
virtual void Deploy (cyclus::Model *parent)
perform module-specific tasks when entering the simulation
virtual std::set
< cyclus::BidPortfolio
< cyclus::Material >::Ptr > GetMatlBids (const cyclus::CommodMap< cyclus::Material >::type &commod_requests)
Responds to each request for this facility's commodity.
virtual std::set
< cyclus::RequestPortfolio
< cyclus::Material >::Ptr > GetMatlRequests ()
The EnrichmentFacility request Materials of its given commodity.
virtual void GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > &trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > &responses)
respond to each trade with a material enriched to the appropriate level given this facility's inventory
std::string in_commodity ()
double in_core_loading ()
std::string in_recipe ()
virtual void InitModuleMembers (cyclus::QueryEngine *qe)
Initialize members related to derived module class.
InproReactor (cyclus::Context *ctx)
Constructor for the InproReactor class.
std::string out_commodity ()
double out_core_loading ()
std::string out_recipe ()
Phase phase ()
int refuel_delay ()
virtual std::string schema ()
void set_batches_per_core (int n)
set the number of batches per core
void set_cycle_length (int time)
set the cycle length
void set_in_commodity (std::string name)
set the input commodity
void set_in_core_loading (double size)
set the input core loading
void set_in_recipe (std::string name)
set the input recipe
void set_out_commodity (std::string name)
set the output commodity
void set_out_core_loading (double size)
set the output core loading
void set_out_recipe (std::string name)
set the output recipe
void set_refuel_delay (int time)
set the time required to refuel the reactor
void SetPhase (Phase p)
set the next phase
virtual std::string str ()
Print information about this model.
virtual void Tick (int time)
The Tick function specific to the BatchReactor.
virtual void Tock (int time)
The Tick function specific to the BatchReactor.
virtual ~InproReactor ()
Destructor for the InproReactor class.
Protected Member Functions
virtual bool CheckDecommissionCondition ()
facilities over write this method if a condition must be met before their destructors can be called
cyclus::BidPortfolio
< cyclus::Material >::Ptr GetBids_ (const cyclus::CommodMap< cyclus::Material >::type &commod_requests, std::string commod, cyclus::ResourceBuff *buffer)
gets bids for a commodity from a buffer
cyclus::RequestPortfolio
< cyclus::Material >::Ptr GetOrder_ (double size)
construct a request portfolio for an order of a given size
cyclus::Material::Ptr TradeResponse_ (double qty, cyclus::ResourceBuff *buffer)
returns a qty of material from the a buffer
Private Member Functions
void LoadCore ()
load fuel from preCore_ into inCore_
void OffloadBatch ()
move a batch from inCore_ to postCore_
void OffloadCore ()
move all material from inCore_ to postCore_
void reset_cycle_timer ()
resets the cycle timer
void SetUpPhaseNames ()
populate the phase name map
Private Attributes
int batches_per_core_
batches per core
int cycle_length_
The time between batch reloadings.
int cycle_timer_
The current time step in the cycle.
std::string in_commodity_
the name of the input commodity
double in_core_loading_
The total mass per core upon entry.
std::string in_recipe_
the name of the input recipe
cyclus::ResourceBuff inCore_
a matbuff for material while they are inside the core
std::string out_commodity_
the name of the output commodity
double out_core_loading_
The total mass per core upon exit.
std::string out_recipe_
the name of the output recipe
Phase phase_
The current phase this facility is in.
cyclus::ResourceBuff postCore_
a matbuff for material after they exit the core
cyclus::ResourceBuff preCore_
a matbuff for material before they enter the core
int refuel_delay_
The time required to refuel the reactor.
cyclus::Material::Ptr staged_precore_
int time_delayed_
The time the present reactor has spent in phase REFUEL_DELAY.
Static Private Attributes
static std::map< Phase,
std::string > phase_names_
a map of phase names
Detailed Description
This class is identical to the RecipeReactor, except that it operates in a batch-like manner, i.e.
it refuels in batches.
Definition at line 32 of file inpro_reactor.h.
Constructor & Destructor Documentation
cycamore::InproReactor::InproReactor (cyclus::Context * ctx)
Constructor for the InproReactor class.
Parameters:
ctx the cyclus context for access to simulation-wide parameters
Definition at line 23 of file inpro_reactor.cc.
References inCore_, phase_names_, postCore_, preCore_, and SetUpPhaseNames().
Referenced by Clone().
cycamore::InproReactor::~InproReactor () [virtual]
Destructor for the InproReactor class.
Definition at line 46 of file inpro_reactor.cc.
Member Function Documentation
void cycamore::InproReactor::AcceptMatlTrades (const std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
The EnrichmentFacility place accepted trade Materials in their Inventory.
Definition at line 283 of file inpro_reactor.cc.
References preCore_.
int cycamore::InproReactor::batches_per_core ()
Returns:
the number of batches per core
Definition at line 435 of file inpro_reactor.cc.
References batches_per_core_.
Referenced by Clone(), and str().
double cycamore::InproReactor::BatchLoading ()
return the batch loading
Definition at line 440 of file inpro_reactor.cc.
References batches_per_core_, and in_core_loading_.
Referenced by LoadCore().
bool cycamore::InproReactor::CheckDecommissionCondition () [protected, virtual]
facilities over write this method if a condition must be met before their destructors can be called
Definition at line 490 of file inpro_reactor.cc.
References inCore_, postCore_, and preCore_.
cyclus::Model * cycamore::InproReactor::Clone () [virtual]
Definition at line 154 of file inpro_reactor.cc.
References batches_per_core(), cycle_length(), in_commodity(), in_core_loading(), in_recipe(), InproReactor(), out_commodity(), out_core_loading(), out_recipe(), refuel_delay(), set_batches_per_core(), set_cycle_length(), set_in_commodity(), set_in_core_loading(), set_in_recipe(), set_out_commodity(), set_out_core_loading(), set_out_recipe(), and set_refuel_delay().
bool cycamore::InproReactor::CoreFilled ()
return true if the core is filled
Definition at line 532 of file inpro_reactor.cc.
References inCore_.
Referenced by Tock().
int cycamore::InproReactor::cycle_length ()
Returns:
the cycle length
Definition at line 395 of file inpro_reactor.cc.
References cycle_length_.
Referenced by Clone(), and str().
bool cycamore::InproReactor::CycleComplete ()
return true if the cycle timer is >= the cycle length
Definition at line 527 of file inpro_reactor.cc.
References cycle_length_, and cycle_timer_.
Referenced by Tock().
void cycamore::InproReactor::Deploy (cyclus::Model * parent) [virtual]
perform module-specific tasks when entering the simulation
Definition at line 173 of file inpro_reactor.cc.
References cycamore::BEGIN, cycle_timer_, in_core_loading(), inCore_, out_core_loading(), phase_, phase_names_, preCore_, reset_cycle_timer(), and SetPhase().
cyclus::BidPortfolio< cyclus::Material >::Ptr cycamore::InproReactor::GetBids_ (const cyclus::CommodMap< cyclus::Material >::type & commod_requests, std::string commod, cyclus::ResourceBuff * buffer) [protected]
gets bids for a commodity from a buffer
Definition at line 571 of file inpro_reactor.cc.
Referenced by GetMatlBids().
std::set< cyclus::BidPortfolio< cyclus::Material >::Ptr > cycamore::InproReactor::GetMatlBids (const cyclus::CommodMap< cyclus::Material >::type & commod_requests) [virtual]
Responds to each request for this facility's commodity.
If a given request is more than this facility's inventory or SWU capacity, it will offer its minimum of its capacities.
Definition at line 261 of file inpro_reactor.cc.
References GetBids_(), out_commodity_, and postCore_.
std::set< cyclus::RequestPortfolio< cyclus::Material >::Ptr > cycamore::InproReactor::GetMatlRequests () [virtual]
The EnrichmentFacility request Materials of its given commodity.
Definition at line 243 of file inpro_reactor.cc.
References GetOrder_(), in_commodity_, in_core_loading(), inCore_, and preCore_.
void cycamore::InproReactor::GetMatlTrades (const std::vector< cyclus::Trade< cyclus::Material > > & trades, std::vector< std::pair< cyclus::Trade< cyclus::Material >, cyclus::Material::Ptr > > & responses) [virtual]
respond to each trade with a material enriched to the appropriate level given this facility's inventory
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 303 of file inpro_reactor.cc.
References out_commodity_, postCore_, and TradeResponse_().
cyclus::RequestPortfolio< cyclus::Material >::Ptr cycamore::InproReactor::GetOrder_ (double size) [protected]
construct a request portfolio for an order of a given size
Definition at line 546 of file inpro_reactor.cc.
References in_commodity_, and in_recipe_.
Referenced by GetMatlRequests().
std::string cycamore::InproReactor::in_commodity ()
Returns:
the input commodity
Definition at line 450 of file inpro_reactor.cc.
References in_commodity_.
Referenced by Clone(), and str().
double cycamore::InproReactor::in_core_loading ()
Returns:
the input core loading in kilograms
Definition at line 415 of file inpro_reactor.cc.
References in_core_loading_.
Referenced by Clone(), Deploy(), GetMatlRequests(), InitModuleMembers(), OffloadBatch(), and str().
std::string cycamore::InproReactor::in_recipe ()
Returns:
the input recipe
Definition at line 460 of file inpro_reactor.cc.
References in_recipe_.
Referenced by Clone().
void cycamore::InproReactor::InitModuleMembers (cyclus::QueryEngine * qe) [virtual]
Initialize members related to derived module class.
Parameters:
qe a pointer to a cyclus::QueryEngine object containing initialization data
Definition at line 97 of file inpro_reactor.cc.
References in_core_loading(), refuel_delay(), set_batches_per_core(), set_cycle_length(), set_in_commodity(), set_in_core_loading(), set_in_recipe(), set_out_commodity(), set_out_core_loading(), set_out_recipe(), and set_refuel_delay().
Referenced by InproReactorTest::InitSrcFacility().
void cycamore::InproReactor::LoadCore () [private]
load fuel from preCore_ into inCore_
Definition at line 650 of file inpro_reactor.cc.
References BatchLoading(), inCore_, and preCore_.
Referenced by Tock().
void cycamore::InproReactor::OffloadBatch () [private]
move a batch from inCore_ to postCore_
Definition at line 636 of file inpro_reactor.cc.
References in_core_loading(), inCore_, out_core_loading(), out_recipe(), and postCore_.
Referenced by OffloadCore(), and Tick().
void cycamore::InproReactor::OffloadCore () [private]
move all material from inCore_ to postCore_
Definition at line 668 of file inpro_reactor.cc.
References inCore_, OffloadBatch(), postCore_, and preCore_.
Referenced by Tick().
std::string cycamore::InproReactor::out_commodity ()
Returns:
the output commodity
Definition at line 470 of file inpro_reactor.cc.
References out_commodity_.
Referenced by Clone(), and str().
double cycamore::InproReactor::out_core_loading ()
Returns:
the output core loading out kilograms
Definition at line 425 of file inpro_reactor.cc.
References out_core_loading_.
Referenced by Clone(), Deploy(), OffloadBatch(), and str().
std::string cycamore::InproReactor::out_recipe ()
Returns:
the output recipe
Definition at line 480 of file inpro_reactor.cc.
References out_recipe_.
Referenced by Clone(), and OffloadBatch().
Phase cycamore::InproReactor::phase ()
Returns:
the current phase
Definition at line 485 of file inpro_reactor.cc.
References phase_.
Referenced by Tick(), and Tock().
int cycamore::InproReactor::refuel_delay ()
Returns:
the refuel delay time
Definition at line 405 of file inpro_reactor.cc.
References refuel_delay_.
Referenced by Clone(), InitModuleMembers(), str(), and Tock().
void cycamore::InproReactor::reset_cycle_timer () [private]
resets the cycle timer
Definition at line 522 of file inpro_reactor.cc.
References cycle_timer_.
Referenced by Deploy(), and Tock().
std::string cycamore::InproReactor::schema () [virtual]
Definition at line 49 of file inpro_reactor.cc.
void cycamore::InproReactor::set_batches_per_core (int n)
set the number of batches per core
Parameters:
n the number of batches to set
Definition at line 430 of file inpro_reactor.cc.
References batches_per_core_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_cycle_length (int time)
set the cycle length
Parameters:
time the cycle length time
Definition at line 390 of file inpro_reactor.cc.
References cycle_length_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_in_commodity (std::string name)
set the input commodity
Parameters:
name the commodity name
Definition at line 445 of file inpro_reactor.cc.
References in_commodity_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_in_core_loading (double size)
set the input core loading
Parameters:
size the core loading size in kilograms
Definition at line 410 of file inpro_reactor.cc.
References in_core_loading_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_in_recipe (std::string name)
set the input recipe
Parameters:
name the recipe name
Definition at line 455 of file inpro_reactor.cc.
References in_recipe_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_out_commodity (std::string name)
set the output commodity
Parameters:
name the commodity name
Definition at line 465 of file inpro_reactor.cc.
References out_commodity_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_out_core_loading (double size)
set the output core loading
Parameters:
size the core loading size out kilograms
Definition at line 420 of file inpro_reactor.cc.
References out_core_loading_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_out_recipe (std::string name)
set the output recipe
Parameters:
name the recipe name
Definition at line 475 of file inpro_reactor.cc.
References out_recipe_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::set_refuel_delay (int time)
set the time required to refuel the reactor
Parameters:
time the refuel delay time
Definition at line 400 of file inpro_reactor.cc.
References refuel_delay_.
Referenced by Clone(), and InitModuleMembers().
void cycamore::InproReactor::SetPhase (Phase p)
set the next phase
Parameters:
p the next phase
Definition at line 501 of file inpro_reactor.cc.
References phase_, and phase_names_.
Referenced by Deploy(), Tick(), and Tock().
void cycamore::InproReactor::SetUpPhaseNames () [private]
populate the phase name map
Definition at line 510 of file inpro_reactor.cc.
References cycamore::BEGIN, cycamore::END, cycamore::INIT, cycamore::OPERATION, phase_names_, cycamore::REFUEL, cycamore::REFUEL_DELAY, and cycamore::WAITING.
Referenced by InproReactor().
std::string cycamore::InproReactor::str () [virtual]
Print information about this model.
Definition at line 138 of file inpro_reactor.cc.
References batches_per_core(), cycle_length(), in_commodity(), in_core_loading(), out_commodity(), out_core_loading(), and refuel_delay().
void cycamore::InproReactor::Tick (int time) [virtual]
The Tick function specific to the BatchReactor.
Parameters:
time the time of the tick
Definition at line 194 of file inpro_reactor.cc.
References cycamore::BEGIN, cycle_timer_, cycamore::END, cycamore::INIT, OffloadBatch(), OffloadCore(), cycamore::OPERATION, phase(), phase_, phase_names_, cycamore::REFUEL, cycamore::REFUEL_DELAY, SetPhase(), and cycamore::WAITING.
void cycamore::InproReactor::Tock (int time) [virtual]
The Tick function specific to the BatchReactor.
Parameters:
time the time of the tock
Definition at line 326 of file inpro_reactor.cc.
References cycamore::BEGIN, CoreFilled(), cycle_timer_, CycleComplete(), cycamore::END, LoadCore(), cycamore::OPERATION, phase(), phase_, phase_names_, cycamore::REFUEL, cycamore::REFUEL_DELAY, refuel_delay(), reset_cycle_timer(), SetPhase(), time_delayed_, and cycamore::WAITING.
cyclus::Material::Ptr cycamore::InproReactor::TradeResponse_ (double qty, cyclus::ResourceBuff * buffer) [protected]
returns a qty of material from the a buffer
Definition at line 613 of file inpro_reactor.cc.
Referenced by GetMatlTrades().
Member Data Documentation
int cycamore::InproReactor::batches_per_core_ [private]
batches per core
Definition at line 276 of file inpro_reactor.h.
Referenced by batches_per_core(), BatchLoading(), and set_batches_per_core().
int cycamore::InproReactor::cycle_length_ [private]
The time between batch reloadings.
Definition at line 267 of file inpro_reactor.h.
Referenced by cycle_length(), CycleComplete(), and set_cycle_length().
int cycamore::InproReactor::cycle_timer_ [private]
The current time step in the cycle.
Definition at line 297 of file inpro_reactor.h.
Referenced by CycleComplete(), Deploy(), reset_cycle_timer(), Tick(), and Tock().
std::string cycamore::InproReactor::in_commodity_ [private]
the name of the input commodity
Definition at line 285 of file inpro_reactor.h.
Referenced by GetMatlRequests(), GetOrder_(), in_commodity(), and set_in_commodity().
double cycamore::InproReactor::in_core_loading_ [private]
The total mass per core upon entry.
Definition at line 279 of file inpro_reactor.h.
Referenced by BatchLoading(), in_core_loading(), and set_in_core_loading().
std::string cycamore::InproReactor::in_recipe_ [private]
the name of the input recipe
Definition at line 288 of file inpro_reactor.h.
Referenced by GetOrder_(), in_recipe(), and set_in_recipe().
cyclus::ResourceBuff cycamore::InproReactor::inCore_ [private]
a matbuff for material while they are inside the core
Definition at line 306 of file inpro_reactor.h.
Referenced by CheckDecommissionCondition(), CoreFilled(), Deploy(), GetMatlRequests(), InproReactor(), LoadCore(), OffloadBatch(), and OffloadCore().
std::string cycamore::InproReactor::out_commodity_ [private]
the name of the output commodity
Definition at line 291 of file inpro_reactor.h.
Referenced by GetMatlBids(), GetMatlTrades(), out_commodity(), and set_out_commodity().
double cycamore::InproReactor::out_core_loading_ [private]
The total mass per core upon exit.
Definition at line 282 of file inpro_reactor.h.
Referenced by out_core_loading(), and set_out_core_loading().
std::string cycamore::InproReactor::out_recipe_ [private]
the name of the output recipe
Definition at line 294 of file inpro_reactor.h.
Referenced by out_recipe(), and set_out_recipe().
Phase cycamore::InproReactor::phase_ [private]
The current phase this facility is in.
Definition at line 300 of file inpro_reactor.h.
Referenced by Deploy(), phase(), SetPhase(), Tick(), and Tock().
std::map< Phase, std::string > cycamore::InproReactor::phase_names_ [static, private]
Initial value:
  std::map<Phase, std::string>()
a map of phase names
Definition at line 262 of file inpro_reactor.h.
Referenced by Deploy(), InproReactor(), SetPhase(), SetUpPhaseNames(), Tick(), and Tock().
cyclus::ResourceBuff cycamore::InproReactor::postCore_ [private]
a matbuff for material after they exit the core
Definition at line 309 of file inpro_reactor.h.
Referenced by CheckDecommissionCondition(), GetMatlBids(), GetMatlTrades(), InproReactor(), OffloadBatch(), and OffloadCore().
cyclus::ResourceBuff cycamore::InproReactor::preCore_ [private]
a matbuff for material before they enter the core
Definition at line 303 of file inpro_reactor.h.
Referenced by AcceptMatlTrades(), CheckDecommissionCondition(), Deploy(), GetMatlRequests(), InproReactor(), LoadCore(), and OffloadCore().
int cycamore::InproReactor::refuel_delay_ [private]
The time required to refuel the reactor.
Definition at line 270 of file inpro_reactor.h.
Referenced by refuel_delay(), and set_refuel_delay().
cyclus::Material::Ptr cycamore::InproReactor::staged_precore_ [private]
Definition at line 264 of file inpro_reactor.h.
int cycamore::InproReactor::time_delayed_ [private]
The time the present reactor has spent in phase REFUEL_DELAY.
Definition at line 273 of file inpro_reactor.h.
Referenced by Tock().
The documentation for this class was generated from the following files:
inpro_reactor.h
inpro_reactor.cc