cycamore: SourceFacilityTest Class Reference
SourceFacilityTest Class Reference
#include <source_facility_tests.h>
Public Member Functions
boost::shared_ptr
< cyclus::ExchangeContext
< cyclus::Material > > GetContext (int nreqs, std::string commodity)
void InitParameters ()
virtual void SetUp ()
void SetUpSourceFacility ()
virtual void TearDown ()
Public Attributes
double capacity
std::string commod
cyclus::Composition::Ptr recipe
std::string recipe_name
cycamore::SourceFacility * src_facility
cyclus::TestContext tc
Detailed Description
Definition at line 18 of file source_facility_tests.h.
Member Function Documentation
boost::shared_ptr< cyclus::ExchangeContext< cyclus::Material > > SourceFacilityTest::GetContext (int nreqs, std::string commodity)
Definition at line 195 of file source_facility_tests.cc.
void SourceFacilityTest::InitParameters ()
Definition at line 25 of file source_facility_tests.cc.
References capacity, commod, recipe, recipe_name, and tc.
Referenced by SetUp().
void SourceFacilityTest::SetUp () [virtual]
Definition at line 14 of file source_facility_tests.cc.
References InitParameters(), and SetUpSourceFacility().
void SourceFacilityTest::SetUpSourceFacility ()
Definition at line 35 of file source_facility_tests.cc.
References capacity, cycamore::SourceFacility::capacity(), commod, cycamore::SourceFacility::commodity(), cycamore::SourceFacility::recipe(), recipe_name, src_facility, and tc.
Referenced by SetUp().
void SourceFacilityTest::TearDown () [virtual]
Definition at line 20 of file source_facility_tests.cc.
References src_facility.
Member Data Documentation
double SourceFacilityTest::capacity
Definition at line 23 of file source_facility_tests.h.
Referenced by InitParameters(), and SetUpSourceFacility().
std::string SourceFacilityTest::commod
Definition at line 22 of file source_facility_tests.h.
Referenced by InitParameters(), and SetUpSourceFacility().
cyclus::Composition::Ptr SourceFacilityTest::recipe
Definition at line 24 of file source_facility_tests.h.
Referenced by InitParameters().
std::string SourceFacilityTest::recipe_name
Definition at line 22 of file source_facility_tests.h.
Referenced by InitParameters(), and SetUpSourceFacility().
cycamore::SourceFacility* SourceFacilityTest::src_facility
Definition at line 21 of file source_facility_tests.h.
Referenced by SetUpSourceFacility(), and TearDown().
cyclus::TestContext SourceFacilityTest::tc
Definition at line 20 of file source_facility_tests.h.
Referenced by InitParameters(), and SetUpSourceFacility().
The documentation for this class was generated from the following files:
source_facility_tests.h
source_facility_tests.cc