cycamore: cycamore::GrowthRegion Class Reference
cycamore::GrowthRegion Class Reference
#include <growth_region.h>
Public Member Functions
void AddCommodityDemand (cyclus::Commodity commod)
add a demand for a commodity on which this region request that facilities be built
virtual cyclus::Model * Clone ()
virtual void Deploy (cyclus::Model *parent)
perform module-specific tasks when entering the simulation
GrowthRegion (cyclus::Context *ctx)
The default constructor for the GrowthRegion.
void InitFrom (GrowthRegion *m)
virtual void InitModuleMembers (cyclus::QueryEngine *qe)
Initialize members related to derived module class.
virtual std::string schema ()
virtual void Tick (int time)
On each tick, the GrowthRegion queries its supply demand manager to determine if there exists some demand.
virtual ~GrowthRegion ()
The default destructor for the GrowthRegion.
Protected Member Functions
void OrderBuild (cyclus::Model *builder, cyclus::Model *prototype)
orders builder to build a prototype
void OrderBuilds (cyclus::Commodity &commodity, double unmetdemand)
orders builds given a commodity and an unmet demand for production capacity of that commodity
void RegisterBuilder (cyclus::Model *model)
register a child as a builder if it is one
void RegisterCommodity (cyclus::Commodity &commodity)
register a commodity for which production capacity is being demanded region
void RegisterCommodityProducerManager (cyclus::Model *model)
register a child as a commodity producer manager if it is one
Protected Attributes
cyclus::BuildingManager buildmanager_
manager for building things
std::set< cyclus::Commodity,
cyclus::CommodityCompare > commodities_
a container of all commodities managed by region
std::map< std::string,
std::vector< DemandInfo > > demands_
cyclus::SupplyDemandManager sdmanager_
manager for Supply and emand
Friends
class GrowthRegionTests
Detailed Description
Definition at line 39 of file growth_region.h.
Constructor & Destructor Documentation
cycamore::GrowthRegion::GrowthRegion (cyclus::Context * ctx)
The default constructor for the GrowthRegion.
Definition at line 17 of file growth_region.cc.
Referenced by Clone().
cycamore::GrowthRegion::~GrowthRegion () [virtual]
The default destructor for the GrowthRegion.
Definition at line 22 of file growth_region.cc.
Member Function Documentation
void cycamore::GrowthRegion::AddCommodityDemand (cyclus::Commodity commod)
add a demand for a commodity on which this region request that facilities be built
Definition at line 88 of file growth_region.cc.
References demands_, cycamore::DemandInfo::params, sdmanager_, cycamore::DemandInfo::time, and cycamore::DemandInfo::type.
Referenced by Deploy().
virtual cyclus::Model* cycamore::GrowthRegion::Clone () [inline, virtual]
Definition at line 85 of file growth_region.h.
References GrowthRegion(), and InitFrom().
void cycamore::GrowthRegion::Deploy (cyclus::Model * parent) [virtual]
perform module-specific tasks when entering the simulation
Definition at line 105 of file growth_region.cc.
References AddCommodityDemand(), commodities_, RegisterBuilder(), and RegisterCommodityProducerManager().
Referenced by cycamore::GrowthRegionTests::InitRegion().
void cycamore::GrowthRegion::InitFrom (GrowthRegion * m)
Definition at line 81 of file growth_region.cc.
References commodities_, and demands_.
Referenced by Clone().
void cycamore::GrowthRegion::InitModuleMembers (cyclus::QueryEngine * qe) [virtual]
Initialize members related to derived module class.
Parameters:
qe a pointer to a cyclus::QueryEngine object containing initialization data
Definition at line 55 of file growth_region.cc.
References commodities_, demands_, cycamore::DemandInfo::params, cycamore::DemandInfo::time, and cycamore::DemandInfo::type.
Referenced by cycamore::GrowthRegionTests::InitRegion().
void cycamore::GrowthRegion::OrderBuild (cyclus::Model * builder, cyclus::Model * prototype) [protected]
orders builder to build a prototype
Parameters:
builder the model that can build buildee
prototype the model to be built
void cycamore::GrowthRegion::OrderBuilds (cyclus::Commodity & commodity, double unmetdemand) [protected]
orders builds given a commodity and an unmet demand for production capacity of that commodity
Parameters:
commodity the commodity being demanded
unmetdemand the unmet demand
Definition at line 175 of file growth_region.cc.
References buildmanager_.
Referenced by Tick().
void cycamore::GrowthRegion::RegisterBuilder (cyclus::Model * model) [protected]
register a child as a builder if it is one
Parameters:
model the child to register
Definition at line 165 of file growth_region.cc.
References buildmanager_.
Referenced by Deploy().
void cycamore::GrowthRegion::RegisterCommodity (cyclus::Commodity & commodity) [protected]
register a commodity for which production capacity is being demanded region
Parameters:
commodity a reference to the commodity
Definition at line 145 of file growth_region.cc.
References commodities_.
void cycamore::GrowthRegion::RegisterCommodityProducerManager (cyclus::Model * model) [protected]
register a child as a commodity producer manager if it is one
Parameters:
model the child to register
Definition at line 155 of file growth_region.cc.
References sdmanager_.
Referenced by Deploy().
std::string cycamore::GrowthRegion::schema () [virtual]
Definition at line 25 of file growth_region.cc.
void cycamore::GrowthRegion::Tick (int time) [virtual]
On each tick, the GrowthRegion queries its supply demand manager to determine if there exists some demand.
If demand for a commodity exists, then the correct build order for that demand is constructed and executed.
Parameters:
time is the time to perform the tick
Definition at line 120 of file growth_region.cc.
References commodities_, OrderBuilds(), and sdmanager_.
Friends And Related Function Documentation
friend class GrowthRegionTests [friend]
Definition at line 40 of file growth_region.h.
Member Data Documentation
cyclus::BuildingManager cycamore::GrowthRegion::buildmanager_ [protected]
manager for building things
Definition at line 101 of file growth_region.h.
Referenced by OrderBuilds(), and RegisterBuilder().
std::set<cyclus::Commodity, cyclus::CommodityCompare> cycamore::GrowthRegion::commodities_ [protected]
a container of all commodities managed by region
Definition at line 96 of file growth_region.h.
Referenced by Deploy(), InitFrom(), InitModuleMembers(), RegisterCommodity(), and Tick().
std::map<std::string, std::vector<DemandInfo> > cycamore::GrowthRegion::demands_ [protected]
Definition at line 98 of file growth_region.h.
Referenced by AddCommodityDemand(), InitFrom(), and InitModuleMembers().
cyclus::SupplyDemandManager cycamore::GrowthRegion::sdmanager_ [protected]
manager for Supply and emand
Definition at line 104 of file growth_region.h.
Referenced by AddCommodityDemand(), cycamore::GrowthRegionTests::ManagesCommodity(), RegisterCommodityProducerManager(), and Tick().
The documentation for this class was generated from the following files:
growth_region.h
growth_region.cc