cycamore: SinkFacilityTest Class Reference
SinkFacilityTest Class Reference
#include <sink_facility_tests.h>
Protected Member Functions
void InitParameters ()
virtual void SetUp ()
void SetUpSinkFacility ()
virtual void TearDown ()
Protected Attributes
double capacity_
std::string commod1_
std::string commod2_
std::string commod3_
double inv_
int ncommods_
double qty_
cycamore::SinkFacility * src_facility
cyclus::TestContext tc_
Detailed Description
Definition at line 9 of file sink_facility_tests.h.
Member Function Documentation
void SinkFacilityTest::InitParameters () [protected]
Definition at line 24 of file sink_facility_tests.cc.
References capacity_, commod1_, commod2_, commod3_, inv_, ncommods_, and qty_.
Referenced by SetUp().
void SinkFacilityTest::SetUp () [protected, virtual]
Definition at line 13 of file sink_facility_tests.cc.
References InitParameters(), and SetUpSinkFacility().
void SinkFacilityTest::SetUpSinkFacility () [protected]
Definition at line 35 of file sink_facility_tests.cc.
References cycamore::SinkFacility::AddCommodity(), cycamore::SinkFacility::capacity(), capacity_, commod1_, commod2_, inv_, cycamore::SinkFacility::SetMaxInventorySize(), src_facility, and tc_.
Referenced by SetUp().
void SinkFacilityTest::TearDown () [protected, virtual]
Definition at line 19 of file sink_facility_tests.cc.
References src_facility.
Member Data Documentation
double SinkFacilityTest::capacity_ [protected]
Definition at line 14 of file sink_facility_tests.h.
Referenced by InitParameters(), and SetUpSinkFacility().
std::string SinkFacilityTest::commod1_ [protected]
Definition at line 13 of file sink_facility_tests.h.
Referenced by InitParameters(), and SetUpSinkFacility().
std::string SinkFacilityTest::commod2_ [protected]
Definition at line 13 of file sink_facility_tests.h.
Referenced by InitParameters(), and SetUpSinkFacility().
std::string SinkFacilityTest::commod3_ [protected]
Definition at line 13 of file sink_facility_tests.h.
Referenced by InitParameters().
double SinkFacilityTest::inv_ [protected]
Definition at line 14 of file sink_facility_tests.h.
Referenced by InitParameters(), and SetUpSinkFacility().
int SinkFacilityTest::ncommods_ [protected]
Definition at line 15 of file sink_facility_tests.h.
Referenced by InitParameters().
double SinkFacilityTest::qty_ [protected]
Definition at line 14 of file sink_facility_tests.h.
Referenced by InitParameters().
cycamore::SinkFacility* SinkFacilityTest::src_facility [protected]
Definition at line 12 of file sink_facility_tests.h.
Referenced by SetUpSinkFacility(), and TearDown().
cyclus::TestContext SinkFacilityTest::tc_ [protected]
Definition at line 11 of file sink_facility_tests.h.
Referenced by SetUpSinkFacility().
The documentation for this class was generated from the following files:
sink_facility_tests.h
sink_facility_tests.cc