cycamore: run_inputs Namespace Reference
run_inputs Namespace Reference
Classes
class Summary
class TestFile
Functions
def check_inputs
def clean_catalogs
def copy_catalogs
def get_files
def main
def print_usage
Function Documentation
def run_inputs.check_inputs ()
This function checks the input arguments
Definition at line 24 of file run_inputs.py.
References print_usage().
Referenced by main().
def run_inputs.clean_catalogs (cyclus_path, catalogs)
Removes previously copied catalogs from executable directory.
Definition at line 85 of file run_inputs.py.
Referenced by main().
def run_inputs.copy_catalogs (catalogs, cyclus_path)
Copies files in the catalogs list to the cyclus executable directory
Definition at line 79 of file run_inputs.py.
Referenced by main().
def run_inputs.get_files (path)
This function walks the 'path' tree and finds input files
Definition at line 55 of file run_inputs.py.
Referenced by main().
def run_inputs.main ()
This function finds input files, runs them, and prints a summary
Definition at line 9 of file run_inputs.py.
References check_inputs(), clean_catalogs(), copy_catalogs(), and get_files().
Referenced by run_inputs.TestFile.no_errors().
def run_inputs.print_usage ()
This prints the proper way to treat the command line interface
Definition at line 39 of file run_inputs.py.
Referenced by check_inputs().