cycamore: cycamore Namespace Reference
cycamore Namespace Reference
Classes
class BatchReactor
class BatchReactorTest
class BuildOrderList
a helper class for storing and extracting build orders
struct DemandInfo
The GrowthRegion class inherits from the RegionModel class and is dynamically loaded by the Model class when requested.
class DeployInst
The DeployInst class inherits from the InstModel class and is dynamically loaded by the Model class when requested.
class EnrichmentFacility
class EnrichmentFacilityTest
class GrowthRegion
class GrowthRegionTests
class InproReactor
This class is identical to the RecipeReactor, except that it operates in a batch-like manner, i.e.
class ManagerInst
class NatUConverter
The NatUConverter is a simple Converter class for material to determine the amount of natural uranium required for their proposed enrichment.
class NullInst
class NullRegion
The NullRegion class inherits from the RegionModel class and is dynamically loaded by the Model class when requested.
class SinkFacility
This cyclus::FacilityModel requests a finite amount of its input commodity.
class SourceFacility
This cyclus::FacilityModel provides a simple source of some capacity (possibly infinite) of some commodity/Recipe.
class SWUConverter
The SWUConverter is a simple Converter class for material to determine the amount of SWU required for their proposed enrichment.
Typedefs
typedef std::pair< std::string,
int > BuildOrder
Enumerations
enum Phase {
INIT, BEGIN, OPERATION, REFUEL,
REFUEL_DELAY, WAITING, END
}
Defines all possible phases this facility can be in.
Functions
cyclus::FacilityModel * BatchReactorConstructor (cyclus::Context *ctx)
cyclus::Model * BatchReactorModelConstructor (cyclus::Context *ctx)
cyclus::Model * ConstructBatchReactor (cyclus::Context *ctx)
cyclus::Model * ConstructDeployInst (cyclus::Context *ctx)
cyclus::Model * ConstructEnrichmentFacility (cyclus::Context *ctx)
cyclus::Model * ConstructGrowthRegion (cyclus::Context *ctx)
cyclus::Model * ConstructInproReactor (cyclus::Context *ctx)
cyclus::Model * ConstructManagerInst (cyclus::Context *ctx)
cyclus::Model * ConstructNullInst (cyclus::Context *ctx)
cyclus::Model * ConstructNullRegion (cyclus::Context *ctx)
cyclus::Model * ConstructSinkFacility (cyclus::Context *ctx)
cyclus::Model * ConstructSourceFacility (cyclus::Context *ctx)
cyclus::FacilityModel * EnrichmentFacilityConstructor (cyclus::Context *ctx)
cyclus::Model * EnrichmentFacilityModelConstructor (cyclus::Context *ctx)
cyclus::RegionModel * GrowthRegionConstructor (cyclus::Context *ctx)
cyclus::Model * GrowthRegionModelConstructor (cyclus::Context *ctx)
INSTANTIATE_TEST_CASE_P (GrowthRegion, RegionModelTests, Values(&GrowthRegionConstructor))
INSTANTIATE_TEST_CASE_P (GrowthRegion, ModelTests, Values(&GrowthRegionModelConstructor))
INSTANTIATE_TEST_CASE_P (BatchReactor, FacilityModelTests, Values(&BatchReactorConstructor))
INSTANTIATE_TEST_CASE_P (BatchReactor, ModelTests, Values(&BatchReactorModelConstructor))
INSTANTIATE_TEST_CASE_P (EnrichmentFac, FacilityModelTests, Values(&EnrichmentFacilityConstructor))
INSTANTIATE_TEST_CASE_P (EnrichmentFac, ModelTests, Values(&EnrichmentFacilityModelConstructor))
bool operator== (const BatchReactor::InitCond &l, const BatchReactor::InitCond &r)
bool operator== (const EnrichmentFacility::InitCond &l, const EnrichmentFacility::InitCond &r)
TEST_F (GrowthRegionTests, init)
TEST_F (EnrichmentFacilityTest, InitialState)
TEST_F (EnrichmentFacilityTest, XMLInit)
TEST_F (EnrichmentFacilityTest, Clone)
TEST_F (EnrichmentFacilityTest, AddMat)
TEST_F (EnrichmentFacilityTest, Request)
TEST_F (BatchReactorTest, InitialState)
TEST_F (BatchReactorTest, XMLInit)
TEST_F (EnrichmentFacilityTest, Offer)
TEST_F (EnrichmentFacilityTest, ValidReq)
TEST_F (EnrichmentFacilityTest, EmptyRequests)
TEST_F (EnrichmentFacilityTest, AddRequests)
TEST_F (BatchReactorTest, Clone)
TEST_F (BatchReactorTest, Print)
TEST_F (BatchReactorTest, Tick)
TEST_F (BatchReactorTest, Tock)
TEST_F (EnrichmentFacilityTest, Extract)
TEST_F (BatchReactorTest, StartProcess)
TEST_F (BatchReactorTest, InitCond)
TEST_F (BatchReactorTest, AddBatches)
TEST_F (EnrichmentFacilityTest, Accept)
TEST_F (BatchReactorTest, BatchInOut)
TEST_F (EnrichmentFacilityTest, AddBids)
TEST_F (EnrichmentFacilityTest, BidConverters)
TEST_F (EnrichmentFacilityTest, Enrich)
TEST_F (EnrichmentFacilityTest, Response)
Typedef Documentation
typedef std::pair<std::string, int> cycamore::BuildOrder
Definition at line 13 of file deploy_inst.h.
Enumeration Type Documentation
enum cycamore::Phase
Defines all possible phases this facility can be in.
Enumerator:
INIT
BEGIN
OPERATION
REFUEL
REFUEL_DELAY
WAITING
END
Definition at line 25 of file inpro_reactor.h.
Function Documentation
cyclus::FacilityModel* cycamore::BatchReactorConstructor (cyclus::Context * ctx)
Definition at line 382 of file batch_reactor_tests.cc.
cyclus::Model* cycamore::BatchReactorModelConstructor (cyclus::Context * ctx)
Definition at line 376 of file batch_reactor_tests.cc.
cyclus::Model* cycamore::ConstructBatchReactor (cyclus::Context * ctx)
Definition at line 865 of file batch_reactor.cc.
cyclus::Model* cycamore::ConstructDeployInst (cyclus::Context * ctx)
Definition at line 115 of file deploy_inst.cc.
cyclus::Model* cycamore::ConstructEnrichmentFacility (cyclus::Context * ctx)
Definition at line 431 of file enrichment_facility.cc.
cyclus::Model* cycamore::ConstructGrowthRegion (cyclus::Context * ctx)
Definition at line 207 of file growth_region.cc.
cyclus::Model* cycamore::ConstructInproReactor (cyclus::Context * ctx)
Definition at line 681 of file inpro_reactor.cc.
cyclus::Model* cycamore::ConstructManagerInst (cyclus::Context * ctx)
Definition at line 75 of file manager_inst.cc.
cyclus::Model* cycamore::ConstructNullInst (cyclus::Context * ctx)
Definition at line 17 of file null_inst.cc.
cyclus::Model* cycamore::ConstructNullRegion (cyclus::Context * ctx)
Definition at line 21 of file null_region.cc.
cyclus::Model* cycamore::ConstructSinkFacility (cyclus::Context * ctx)
Definition at line 226 of file sink_facility.cc.
cyclus::Model* cycamore::ConstructSourceFacility (cyclus::Context * ctx)
Definition at line 182 of file source_facility.cc.
cyclus::FacilityModel* cycamore::EnrichmentFacilityConstructor (cyclus::Context * ctx)
Definition at line 609 of file enrichment_facility_tests.cc.
cyclus::Model* cycamore::EnrichmentFacilityModelConstructor (cyclus::Context * ctx)
Definition at line 603 of file enrichment_facility_tests.cc.
cyclus::RegionModel* cycamore::GrowthRegionConstructor (cyclus::Context * ctx)
Definition at line 36 of file growth_region_tests.cc.
cyclus::Model* cycamore::GrowthRegionModelConstructor (cyclus::Context * ctx)
Definition at line 31 of file growth_region_tests.cc.
cycamore::INSTANTIATE_TEST_CASE_P (GrowthRegion , RegionModelTests , Values & GrowthRegionConstructor)
cycamore::INSTANTIATE_TEST_CASE_P (GrowthRegion , ModelTests , Values & GrowthRegionModelConstructor)
cycamore::INSTANTIATE_TEST_CASE_P (BatchReactor , FacilityModelTests , Values & BatchReactorConstructor)
cycamore::INSTANTIATE_TEST_CASE_P (BatchReactor , ModelTests , Values & BatchReactorModelConstructor)
cycamore::INSTANTIATE_TEST_CASE_P (EnrichmentFac , FacilityModelTests , Values & EnrichmentFacilityConstructor)
cycamore::INSTANTIATE_TEST_CASE_P (EnrichmentFac , ModelTests , Values & EnrichmentFacilityModelConstructor)
bool cycamore::operator== (const BatchReactor::InitCond & l, const BatchReactor::InitCond & r)
Definition at line 18 of file batch_reactor_tests.cc.
References cycamore::BatchReactor::InitCond::core, cycamore::BatchReactor::InitCond::core_commod, cycamore::BatchReactor::InitCond::core_rec, cycamore::BatchReactor::InitCond::n_core, cycamore::BatchReactor::InitCond::n_reserves, cycamore::BatchReactor::InitCond::n_storage, cycamore::BatchReactor::InitCond::reserves, cycamore::BatchReactor::InitCond::reserves_commod, cycamore::BatchReactor::InitCond::reserves_rec, cycamore::BatchReactor::InitCond::storage, cycamore::BatchReactor::InitCond::storage_commod, and cycamore::BatchReactor::InitCond::storage_rec.
bool cycamore::operator== (const EnrichmentFacility::InitCond & l, const EnrichmentFacility::InitCond & r)
Definition at line 18 of file enrichment_facility_tests.cc.
References cycamore::EnrichmentFacility::InitCond::reserves.
cycamore::TEST_F (GrowthRegionTests , init)
Definition at line 69 of file growth_region_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , InitialState)
Definition at line 116 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , XMLInit)
Definition at line 130 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , Clone)
Definition at line 167 of file enrichment_facility_tests.cc.
References cycamore::EnrichmentFacility::commodity_price(), cycamore::EnrichmentFacility::feed_assay(), cycamore::EnrichmentFacility::ics(), cycamore::EnrichmentFacility::in_commodity(), cycamore::EnrichmentFacility::in_recipe(), cycamore::EnrichmentFacility::InventorySize(), cycamore::EnrichmentFacility::MaxInventorySize(), cycamore::EnrichmentFacility::out_commodity(), cycamore::EnrichmentFacility::swu_capacity(), and cycamore::EnrichmentFacility::tails_assay().
cycamore::TEST_F (EnrichmentFacilityTest , AddMat)
Definition at line 188 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , Request)
Definition at line 196 of file enrichment_facility_tests.cc.
cycamore::TEST_F (BatchReactorTest , InitialState)
Definition at line 202 of file batch_reactor_tests.cc.
cycamore::TEST_F (BatchReactorTest , XMLInit)
Definition at line 207 of file batch_reactor_tests.cc.
References cycamore::BatchReactor::InitModuleMembers().
cycamore::TEST_F (EnrichmentFacilityTest , Offer)
Definition at line 219 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , ValidReq)
Definition at line 245 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , EmptyRequests)
Definition at line 272 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , AddRequests)
Definition at line 284 of file enrichment_facility_tests.cc.
cycamore::TEST_F (BatchReactorTest , Clone)
Definition at line 287 of file batch_reactor_tests.cc.
cycamore::TEST_F (BatchReactorTest , Print)
Definition at line 295 of file batch_reactor_tests.cc.
cycamore::TEST_F (BatchReactorTest , Tick)
Definition at line 300 of file batch_reactor_tests.cc.
cycamore::TEST_F (BatchReactorTest , Tock)
Definition at line 311 of file batch_reactor_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , Extract)
Definition at line 315 of file enrichment_facility_tests.cc.
cycamore::TEST_F (BatchReactorTest , StartProcess)
Definition at line 317 of file batch_reactor_tests.cc.
References cycamore::BatchReactor::PROCESS.
cycamore::TEST_F (BatchReactorTest , InitCond)
Definition at line 326 of file batch_reactor_tests.cc.
cycamore::TEST_F (BatchReactorTest , AddBatches)
Definition at line 332 of file batch_reactor_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , Accept)
Definition at line 335 of file enrichment_facility_tests.cc.
cycamore::TEST_F (BatchReactorTest , BatchInOut)
Definition at line 356 of file batch_reactor_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , AddBids)
Definition at line 370 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , BidConverters)
Definition at line 436 of file enrichment_facility_tests.cc.
References cycamore::SWUConverter::convert(), and cycamore::NatUConverter::convert().
cycamore::TEST_F (EnrichmentFacilityTest , Enrich)
Definition at line 467 of file enrichment_facility_tests.cc.
cycamore::TEST_F (EnrichmentFacilityTest , Response)
Definition at line 515 of file enrichment_facility_tests.cc.