cycamore: source_facility_tests.cc File Reference
source_facility_tests.cc File Reference
#include <gtest/gtest.h>
#include <sstream>
#include "cyc_limits.h"
#include "resource_helpers.h"
#include "xml_query_engine.h"
#include "xml_parser.h"
#include "source_facility_tests.h"
Functions
INSTANTIATE_TEST_CASE_P (SourceFac, FacilityModelTests, Values(&SourceFacilityConstructor))
INSTANTIATE_TEST_CASE_P (SourceFac, ModelTests, Values(&SourceFacilityModelConstructor))
cyclus::FacilityModel * SourceFacilityConstructor (cyclus::Context *ctx)
cyclus::Model * SourceFacilityModelConstructor (cyclus::Context *ctx)
TEST_F (SourceFacilityTest, InitialState)
TEST_F (SourceFacilityTest, XMLInit)
TEST_F (SourceFacilityTest, Clone)
TEST_F (SourceFacilityTest, Print)
TEST_F (SourceFacilityTest, GetOffer)
TEST_F (SourceFacilityTest, AddBids)
TEST_F (SourceFacilityTest, Response)
Function Documentation
INSTANTIATE_TEST_CASE_P (SourceFac , FacilityModelTests , Values & SourceFacilityConstructor)
INSTANTIATE_TEST_CASE_P (SourceFac , ModelTests , Values & SourceFacilityModelConstructor)
cyclus::FacilityModel* SourceFacilityConstructor (cyclus::Context * ctx)
Definition at line 216 of file source_facility_tests.cc.
cyclus::Model* SourceFacilityModelConstructor (cyclus::Context * ctx)
Definition at line 210 of file source_facility_tests.cc.
TEST_F (SourceFacilityTest , InitialState)
Definition at line 43 of file source_facility_tests.cc.
TEST_F (SourceFacilityTest , XMLInit)
Definition at line 51 of file source_facility_tests.cc.
TEST_F (SourceFacilityTest , Clone)
Definition at line 72 of file source_facility_tests.cc.
References cycamore::SourceFacility::capacity(), cycamore::SourceFacility::commodity(), cycamore::SourceFacility::current_capacity(), and cycamore::SourceFacility::recipe().
TEST_F (SourceFacilityTest , Print)
Definition at line 86 of file source_facility_tests.cc.
TEST_F (SourceFacilityTest , GetOffer)
Definition at line 91 of file source_facility_tests.cc.
TEST_F (SourceFacilityTest , AddBids)
Definition at line 114 of file source_facility_tests.cc.
TEST_F (SourceFacilityTest , Response)
Definition at line 143 of file source_facility_tests.cc.